### ISSUE TITLE
Application failed to start [Unraid]

### ISSUE THREAD

**Issue by Spontan-TV** [binhex/arch-crafty-4#3]
Here the Log:

++ export PS1
++ VIRTUAL_ENV_PROMPT='(venv) '
++ export VIRTUAL_ENV_PROMPT
++ hash -r

2024-04-01 13:06:27,177 DEBG 'start-script' stderr output:
+ [[ -f /config/crafty/app/config/session.lock ]]
+ echo 'Removing previous session.lock file '\''/config/crafty/app/config/session.lock'\''...'

2024-04-01 13:06:27,177 DEBG 'start-script' stdout output:
Removing previous session.lock file '/config/crafty/app/config/session.lock'...

2024-04-01 13:06:27,177 DEBG 'start-script' stderr output:
+ rm -f /config/crafty/app/config/session.lock

2024-04-01 13:06:27,178 DEBG 'start-script' stderr output:
+ cp /opt/crafty/app/config-backup/version.json /config/crafty/app/config/version.json

2024-04-01 13:06:27,180 DEBG 'start-script' stderr output:
+ python3 /opt/crafty/main.py

2024-04-01 13:06:27,708 DEBG 'start-script' stdout output:
Logging set to: 0

2024-04-01 13:06:27,709 DEBG 'start-script' stdout output:

    ///////////////////////////////////////////////////////////////////////////
    #                  Welcome to Crafty Controller - v.4.3.1                 #
    ///////////////////////////////////////////////////////////////////////////
    #          Server Manager / Web Portal for your Minecraft server          #
    #                     Homepage: www.craftycontrol.com                     #
    ///////////////////////////////////////////////////////////////////////////
    

2024-04-01 13:06:27,711 DEBG 'start-script' stdout output:
[+] Crafty: 01/04/24 13:06:27 - INFO:   Starting migrations

2024-04-01 13:06:27,720 DEBG 'start-script' stdout output:
[+] Crafty: 01/04/24 13:06:27 - INFO:   Migrating Data from Int to UUID (Type Change)

2024-04-01 13:06:27,727 DEBG 'start-script' stdout output:
[+] Crafty: 01/04/24 13:06:27 - INFO:   Migrating Data from Int to UUID (Type Change) : SUCCESS

2024-04-01 13:06:27,729 DEBG 'start-script' stdout output:
[+] Crafty: 01/04/24 13:06:27 - INFO:   Migrating Data from Int to UUID (Foreign Keys)

2024-04-01 13:06:27,949 DEBG 'start-script' stdout output:
[+] Crafty: 01/04/24 13:06:27 - INFO:   Migrating Data from Int to UUID (Foreign Keys) : SUCCESS

2024-04-01 13:06:27,950 DEBG 'start-script' stdout output:
[+] Crafty: 01/04/24 13:06:27 - INFO:   Migrating Data from Int to UUID (Primary Keys)

2024-04-01 13:06:27,951 DEBG 'start-script' stdout output:
[+] Crafty: 01/04/24 13:06:27 - INFO:   Migrating Data from Int to UUID (Primary Keys) : SUCCESS

2024-04-01 13:06:27,952 DEBG 'start-script' stdout output:
[+] Crafty: 01/04/24 13:06:27 - INFO:   Migrating Data from Int to UUID (Removing UUID Field from Servers)

2024-04-01 13:06:27,954 DEBG 'start-script' stderr output:
Traceback (most recent call last):

2024-04-01 13:06:27,954 DEBG 'start-script' stderr output:
  File "/opt/crafty/main.py", line 337, in <module>
    migration_manager.up()  # Automatically runs migrations
    ^^^^^^^^^^^^^^
2024-04-01 13:06:27,954 DEBG 'start-script' stderr output:
^^^^^^^^
  File "/opt/crafty/app/classes/shared/migration.py", line 431, in up
    done.append(self.up_one(mname, self.migrator))
      
2024-04-01 13:06:27,954 DEBG 'start-script' stderr output:
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/crafty/app/classes/shared/migration.py", line 476, in up_one

2024-04-01 13:06:27,954 DEBG 'start-script' stderr output:
    migrate_fn(migrator, self.database)
  File "<string>", line 207, in migrate
  File "/opt/crafty/app/classes/shared/migration.py", line 68, in wrapper

2024-04-01 13:06:27,955 DEBG 'start-script' stderr output:
    return method(migrator, migrator.table_dict[model], *args, **kwargs)
                            ~~~~~~~~~~~~~~~~~~~^^^^^^^

2024-04-01 13:06:27,955 DEBG 'start-script' stderr output:
KeyError: 'servers'

2024-04-01 13:06:28,015 DEBG fd 8 closed, stopped monitoring <POutputDispatcher at 22568512270224 for <Subprocess at 22568512574544 with name start-script in state RUNNING> (stdout)>
2024-04-01 13:06:28,015 DEBG fd 10 closed, stopped monitoring <POutputDispatcher at 22568526252240 for <Subprocess at 22568512574544 with name start-script in state RUNNING> (stderr)>
2024-04-01 13:06:28,015 WARN exited: start-script (exit status 1; not expected)
2024-04-01 13:06:28,015 DEBG received SIGCHLD indicating a child quit



If there is a fix alredy pls leet mee know thx (Real cool Project)

**Comment by Spontan-TV** [comment]
i fixed it by copying all data to pc -> del everything and reinstall so it works i gess
